### ISSUE TITLE
Cache-control for RichUrls::Cache::Wrapper

### ISSUE THREAD

**Issue by grdw** [WeTransfer/richurls#43]
It must be possible for a client to adjust the cache per request. This is currently not the case but it must be possible to add caching options to the `#enrich` method. This will most likely look like:

```ruby
RichUrls.enrich('https://wetransfer.com', cache_time: 0) # meaning no caching
RichUrls.enrich('https://wetransfer.com', cache_time: 3600) # meaning caching for 3600 seconds
RichUrls.enrich('https://wetransfer.com') # meaning default cache
```

The `cache_time` attribute needs to be passed on to the `UrlFetcher` instance and furthermore trickled down to the respective `set` and `extend` methods in the `Cache::Wrapper`.

**Comment by lorenzograndi4** [comment]
What's a scenario where it's useful to make it configurable at every request?

**Comment by grdw** [comment]
The only thing I can see is that it's practical for testing; or if you know a webpage just changed and you want to grab a fresh enriched set of data.
